# Generated by Django 5.2.5 on 2025-10-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credenciales',
            fields=[
                ('idcredenciales', models.AutoField(db_column='idcredenciales', primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'credenciales',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('idhistorial', models.AutoField(db_column='idhistorial', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('alertas_idalertas', models.IntegerField(blank=True, null=True)),
                ('producto_idproducto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historial',
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('idmovimiento', models.AutoField(db_column='idmovimiento', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=400)),
                ('fecha', models.DateTimeField()),
                ('tipo', models.CharField(max_length=45)),
                ('producto_idproducto', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movimiento',
            },
        ),
    ]
