# Generated by Django 5.2.5 on 2025-10-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('idventa', models.AutoField(db_column='idventa', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total', models.IntegerField()),
                ('empleado_idempleado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'venta',
            },
        ),
    ]
