# Generated by Django 5.2.7 on 2025-10-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0002_venta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('idalertas', models.AutoField(db_column='idalertas', primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'alertas',
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('iddetalleVenta', models.AutoField(db_column='iddetalleVenta', primary_key=True, serialize=False)),
                ('cantidad_producto', models.IntegerField()),
                ('precio_unitario', models.IntegerField()),
                ('subtotal', models.IntegerField()),
                ('producto_idproducto', models.IntegerField(blank=True, null=True)),
                ('venta_idventa', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'detalleventa',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idempleado', models.AutoField(db_column='idempleado', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('credenciales_idcredenciales', models.IntegerField(blank=True, null=True)),
                ('tipoEmpleado_idtipoEmpleado', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idproducto', models.AutoField(db_column='idproducto', primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.CharField(max_length=400)),
                ('precio', models.IntegerField()),
                ('stock_actual', models.IntegerField()),
                ('cantidad_minima', models.IntegerField()),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('idtipoEmpleado', models.AutoField(db_column='idtipoEmpleado', primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipoEmpleado',
            },
        ),
    ]
