# Generated by Django 5.2.5 on 2025-11-09 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_alertas_detalleventa_empleado_producto_tipoempleado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleventa',
            name='producto_idproducto',
        ),
        migrations.RemoveField(
            model_name='detalleventa',
            name='venta_idventa',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='credenciales_idcredenciales',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='tipoEmpleado_idtipoEmpleado',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='alertas_idalertas',
        ),
        migrations.RemoveField(
            model_name='historial',
            name='producto_idproducto',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='producto_idproducto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='empleado_idempleado',
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='producto',
            field=models.ForeignKey(blank=True, db_column='producto_idproducto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles', to='Tienda.producto'),
        ),
        migrations.AddField(
            model_name='detalleventa',
            name='venta',
            field=models.ForeignKey(blank=True, db_column='venta_idventa', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles', to='Tienda.venta'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='credenciales',
            field=models.OneToOneField(blank=True, db_column='credenciales_idcredenciales', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleado', to='Tienda.credenciales'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipoEmpleado',
            field=models.ForeignKey(blank=True, db_column='tipoEmpleado_idtipoEmpleado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empleados', to='Tienda.tipoempleado'),
        ),
        migrations.AddField(
            model_name='historial',
            name='alerta',
            field=models.ForeignKey(blank=True, db_column='alertas_idalertas', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales', to='Tienda.alertas'),
        ),
        migrations.AddField(
            model_name='historial',
            name='producto',
            field=models.ForeignKey(blank=True, db_column='producto_idproducto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiales', to='Tienda.producto'),
        ),
        migrations.AddField(
            model_name='movimiento',
            name='producto',
            field=models.ForeignKey(blank=True, db_column='producto_idproducto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='Tienda.producto'),
        ),
        migrations.AddField(
            model_name='venta',
            name='empleado',
            field=models.ForeignKey(blank=True, db_column='empleado_idempleado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='Tienda.empleado'),
        ),
    ]
